# Generated by Django 4.1.3 on 2023-03-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_follow_delete_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followed',
        ),
    ]
